### PR TITLE
2016UL

### PR DESCRIPTION
**Pull request by wrtabb**
Added 2016UL regression to the repository. I believe I did it with minimal changes to be able to do regression for 2016UL, although I made minor edits to plotting scripts and included my own items in .gitignore based on some scripts I created locally that don't need to be in the main repository.

This is my first pull request, so if I failed to follow proper protocol or made any errors, please let me know.

### CODE REVIEW

**Comment by Sam-Harper** [comment]
Thanks Robert. This is much appreicated. However something seems to have gone wrong with the merge so you might have to rebase onto the master. 

do a git pull to make sure you have the lastest head of the master and then create a backup of your branch  

git checkout 2016UL
git checkout -b 2016UL_backup
git checkout 2016UL
git rebase --onto master HEAD~2  

and see if that works

If think this shouldnt change things from your code. If it does, then we make a seperate branch for the 2016UL and tag that. 

I'll have a proper review of it when the rebase is done.

**Comment by wrtabb** [comment]
I did what you suggested; the new 2016UL seems to be the same as the backup branch I created other than the one line I just added to .gitignore.

**Comment by Sam-Harper** [comment]
odd, did you do the first step which was to update the master to the current master?

**Comment by wrtabb** [comment]
I did "git pull" from my master branch, but maybe I misunderstood. This would make sure my master branch locally is the same as my master branch on GitHub, which is the forked repo. But maybe you mean to make sure my master is the same as the master branch at cms-egamma? 

Also, the additional commit above that says "concluding merge" is where I accidentally merged my master and my 2016UL branches. Locally this doesn't cause me any real issues since the differences were minimal to begin with, but I don't know if it will affect what we're trying to do here. The branch 2016UL is still the same as the backup I created.

**Pull request closed without merging**
